"""Tests for yttranscript.mail: email sending via himalaya."""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import patch

import pytest

from yttranscript.mail import (
    EmailError,
    _build_mime,
    _guess_content_type,
    format_body,
    send_email,
    validate_email,
)


# --- validate_email -------------------------------------------------------

def test_validate_email_accepts_simple_address():
    validate_email("user@example.com")  # no exception


def test_validate_email_accepts_plus_and_dots():
    validate_email("first.last+tag@sub.example.co")


@pytest.mark.parametrize(
    "bad",
    [
        "",
        "not-an-email",
        "user@",
        "@example.com",
        "user@example",            # no TLD
        "user name@example.com",   # space
        "a@b@c.com",               # two @
    ],
)
def test_validate_email_rejects_invalid(bad):
    with pytest.raises(EmailError):
        validate_email(bad)


def test_validate_email_strips_whitespace():
    # Trailing/leading whitespace is stripped before matching, so these pass.
    validate_email("  user@example.com  ")


# --- format_body ----------------------------------------------------------

def test_format_body_contains_key_fields():
    body = format_body({
        "title": "My Talk",
        "channel": " chan-name ",
        "url": "https://youtu.be/abc",
        "language": "es",
        "duration": 754,        # 12:34
        "upload_date": "20260614",
    })
    assert "My Talk" in body
    assert "https://youtu.be/abc" in body
    assert "es" in body
    assert "12:34" in body
    assert "2026-06-14" in body


def test_format_body_handles_missing_fields():
    body = format_body({})
    assert "Title:" in body
    assert "unknown" in body  # duration default
    # Should not raise even with empty dict


def test_format_body_omits_url_if_absent():
    body = format_body({"title": "x"})
    assert "URL:" not in body


# --- _guess_content_type --------------------------------------------------

@pytest.mark.parametrize(
    "ext,expected",
    [
        (".txt", "text/plain"),
        (".json", "application/json"),
        (".vtt", "text/vtt"),
        (".srt", "application/x-subrip"),
        (".pdf", "application/pdf"),
        (".epub", "application/epub+zip"),
        (".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        (".xyz", "application/octet-stream"),  # unknown
        ("", "application/octet-stream"),       # no extension
    ],
)
def test_guess_content_type(ext, expected, tmp_path):
    p = tmp_path / f"file{ext}"
    p.write_text("x")
    assert _guess_content_type(p) == expected


# --- _build_mime ----------------------------------------------------------

def test_build_mime_has_attachment_and_body(tmp_path):
    att = tmp_path / "transcript.txt"
    att.write_text("hello world")
    raw = _build_mime(
        to="dest@example.com",
        subject="transcript.txt",
        body="Transcript generated by yttranscript.\n",
        attachment=att,
    )
    msg = raw.decode("utf-8", errors="replace")
    assert "To: dest@example.com" in msg
    assert "Subject: transcript.txt" in msg
    assert "Content-Disposition: attachment" in msg
    assert 'filename="transcript.txt"' in msg
    # Body content must be present (quoted-printable encoded)
    assert "yttranscript" in msg


def test_build_mime_pdf_uses_pdf_mime(tmp_path):
    att = tmp_path / "out.pdf"
    att.write_bytes(b"%PDF-1.4 fake")
    raw = _build_mime("x@y.com", "out.pdf", "body", att)
    assert b"application/pdf" in raw


# --- send_email -----------------------------------------------------------

def _cp(returncode=0, stderr=""):
    return subprocess.CompletedProcess(args=[], returncode=returncode, stdout="", stderr=stderr)


def test_send_email_invokes_himalaya_with_message_send(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("hello")

    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.subprocess.run", return_value=_cp(0)) as mock_run:
        send_email(
            to="user@example.com",
            subject="out.txt",
            body="body text",
            attachment=att,
        )
    cmd = mock_run.call_args[0][0]
    assert cmd[0] == "himalaya"
    assert cmd[1:3] == ["message", "send"]
    # The 4th element is the positional path to the temp .eml file
    eml_path = Path(cmd[3])
    assert eml_path.suffix == ".eml"
    # Temp file is cleaned up after send
    assert not eml_path.exists()


def test_send_email_raises_when_himalaya_missing(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value=None):
        with pytest.raises(EmailError, match="himalaya is required"):
            send_email("a@b.com", "subj", "body", att)


def test_send_email_raises_when_attachment_missing(tmp_path):
    missing = tmp_path / "does_not_exist.txt"
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"):
        with pytest.raises(EmailError, match="Attachment not found"):
            send_email("a@b.com", "subj", "body", missing)


def test_send_email_raises_on_invalid_address(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    # Should fail BEFORE even checking himalaya
    with patch("yttranscript.mail.shutil.which", return_value=None) as mock_which:
        with pytest.raises(EmailError, match="Invalid email address"):
            send_email("not-an-email", "subj", "body", att)
    mock_which.assert_not_called()


def test_send_email_raises_on_himalala_nonzero(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.subprocess.run", return_value=_cp(1, stderr="smtp error")):
        with pytest.raises(EmailError, match="himalaya failed.*smtp error"):
            send_email("a@b.com", "subj", "body", att)


def test_send_email_raises_on_timeout(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.subprocess.run", side_effect=subprocess.TimeoutExpired(cmd=["x"], timeout=1)):
        with pytest.raises(EmailError, match="timed out"):
            send_email("a@b.com", "subj", "body", att, timeout=0.01)


def test_send_email_cleans_up_tempfile_even_on_failure(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    captured_paths: list[str] = []

    def fake_run(cmd, **kwargs):
        # The 4th element is the temp .eml path (positional argument)
        captured_paths.append(cmd[3])
        return _cp(1, stderr="boom")

    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.subprocess.run", side_effect=fake_run):
        with pytest.raises(EmailError):
            send_email("a@b.com", "subj", "body", att)

    # Even though send failed, the .eml temp file was removed
    assert Path(captured_paths[0]).exists() is False
