"""Tests for yttranscript.mail: email sending via himalaya."""

from __future__ import annotations

import subprocess
from unittest.mock import patch

import pytest

from yttranscript.mail import (
    EmailError,
    _build_mime,
    _guess_content_type,
    format_body,
    resolve_sender,
    send_email,
    validate_email,
)


# --- validate_email -------------------------------------------------------

def test_validate_email_accepts_simple_address():
    validate_email("user@example.com")  # no exception


def test_validate_email_accepts_plus_and_dots():
    validate_email("first.last+tag@sub.example.co")


@pytest.mark.parametrize(
    "bad",
    [
        "",
        "not-an-email",
        "user@",
        "@example.com",
        "user@example",            # no TLD
        "user name@example.com",   # space
        "a@b@c.com",               # two @
    ],
)
def test_validate_email_rejects_invalid(bad):
    with pytest.raises(EmailError):
        validate_email(bad)


def test_validate_email_strips_whitespace():
    # Trailing/leading whitespace is stripped before matching, so these pass.
    validate_email("  user@example.com  ")


# --- format_body ----------------------------------------------------------

def test_format_body_contains_key_fields():
    body = format_body({
        "title": "My Talk",
        "channel": " chan-name ",
        "url": "https://youtu.be/abc",
        "language": "es",
        "duration": 754,        # 12:34
        "upload_date": "20260614",
    })
    assert "My Talk" in body
    assert "https://youtu.be/abc" in body
    assert "es" in body
    assert "12:34" in body
    assert "2026-06-14" in body


def test_format_body_handles_missing_fields():
    body = format_body({})
    assert "Title:" in body
    assert "unknown" in body  # duration default
    # Should not raise even with empty dict


def test_format_body_omits_url_if_absent():
    body = format_body({"title": "x"})
    assert "URL:" not in body


# --- _guess_content_type --------------------------------------------------

@pytest.mark.parametrize(
    "ext,expected",
    [
        (".txt", "text/plain"),
        (".json", "application/json"),
        (".vtt", "text/vtt"),
        (".srt", "application/x-subrip"),
        (".pdf", "application/pdf"),
        (".epub", "application/epub+zip"),
        (".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
        (".xyz", "application/octet-stream"),  # unknown
        ("", "application/octet-stream"),       # no extension
    ],
)
def test_guess_content_type(ext, expected, tmp_path):
    p = tmp_path / f"file{ext}"
    p.write_text("x")
    assert _guess_content_type(p) == expected


# --- _build_mime ----------------------------------------------------------

def test_build_mime_has_attachment_and_body(tmp_path):
    att = tmp_path / "transcript.txt"
    att.write_text("hello world")
    raw = _build_mime(
        to="dest@example.com",
        subject="transcript.txt",
        body="Transcript generated by yttranscript.\n",
        attachment=att,
    )
    msg = raw.decode("utf-8", errors="replace")
    assert "To: dest@example.com" in msg
    assert "Subject: transcript.txt" in msg
    assert "Content-Disposition: attachment" in msg
    assert 'filename="transcript.txt"' in msg
    # Body content must be present (quoted-printable encoded)
    assert "yttranscript" in msg


def test_build_mime_pdf_uses_pdf_mime(tmp_path):
    att = tmp_path / "out.pdf"
    att.write_bytes(b"%PDF-1.4 fake")
    raw = _build_mime("x@y.com", "out.pdf", "body", att)
    assert b"application/pdf" in raw


# --- send_email -----------------------------------------------------------

_SENDER = "Test Sender <test@example.com>"


def _cp(returncode=0, stderr=""):
    return subprocess.CompletedProcess(
        args=[], returncode=returncode, stdout=b"", stderr=stderr.encode() if isinstance(stderr, str) else stderr
    )


def test_send_email_invokes_himalaya_with_message_send(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("hello")

    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.resolve_sender", return_value=_SENDER), \
         patch("yttranscript.mail.subprocess.run", return_value=_cp(0)) as mock_run:
        send_email(
            to="user@example.com",
            subject="out.txt",
            body="body text",
            attachment=att,
        )
    args, kwargs = mock_run.call_args
    cmd = args[0] if args else kwargs.get("args")
    assert cmd == ["himalaya", "message", "send"]
    # The MIME message is piped via stdin (bytes), not passed as a file path
    mime_input = kwargs.get("input")
    assert mime_input is not None
    assert b"To: user@example.com" in mime_input
    assert b"Subject: out.txt" in mime_input
    assert b"test@example.com" in mime_input  # From header


def test_send_email_raises_when_himalaya_missing(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value=None):
        with pytest.raises(EmailError, match="himalaya is required"):
            send_email("a@b.com", "subj", "body", att)


def test_send_email_raises_when_attachment_missing(tmp_path):
    missing = tmp_path / "does_not_exist.txt"
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"):
        with pytest.raises(EmailError, match="Attachment not found"):
            send_email("a@b.com", "subj", "body", missing)


def test_send_email_raises_on_invalid_address(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    # Should fail BEFORE even checking himalaya
    with patch("yttranscript.mail.shutil.which", return_value=None) as mock_which:
        with pytest.raises(EmailError, match="Invalid email address"):
            send_email("not-an-email", "subj", "body", att)
    mock_which.assert_not_called()


def test_send_email_raises_on_himalala_nonzero(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.resolve_sender", return_value=_SENDER), \
         patch("yttranscript.mail.subprocess.run", return_value=_cp(1, stderr="smtp error")):
        with pytest.raises(EmailError, match="himalaya failed.*smtp error"):
            send_email("a@b.com", "subj", "body", att)


def test_send_email_raises_on_timeout(tmp_path):
    att = tmp_path / "out.txt"
    att.write_text("x")
    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.resolve_sender", return_value=_SENDER), \
         patch("yttranscript.mail.subprocess.run", side_effect=subprocess.TimeoutExpired(cmd=["x"], timeout=1)):
        with pytest.raises(EmailError, match="timed out"):
            send_email("a@b.com", "subj", "body", att, timeout=0.01)


def test_send_email_does_not_pass_message_as_positional_arg(tmp_path):
    """Regression: himalaya v1.2 ignores positional args when stdin is piped,
    so the MIME must go through stdin — never as a CLI argument."""
    att = tmp_path / "out.txt"
    att.write_text("x")

    with patch("yttranscript.mail.shutil.which", return_value="/usr/bin/himalaya"), \
         patch("yttranscript.mail.resolve_sender", return_value=_SENDER), \
         patch("yttranscript.mail.subprocess.run", return_value=_cp(0)) as mock_run:
        send_email("a@b.com", "subj", "body", att)

    args, kwargs = mock_run.call_args
    cmd = args[0] if args else kwargs.get("args")
    assert len(cmd) == 3  # exactly ["himalaya", "message", "send"], no path


# --- resolve_sender -------------------------------------------------------

def _write_himalaya_config(path, accounts):
    """Write a minimal himalaya config.toml with the given accounts dict."""
    lines = []
    for name, acc in accounts.items():
        lines.append(f"[accounts.{name}]")
        for k, v in acc.items():
            if isinstance(v, bool):
                lines.append(f"{k} = {str(v).lower()}")
            elif isinstance(v, str):
                lines.append(f'{k} = "{v}"')
        lines.append("")
    path.write_text("\n".join(lines))


def test_resolve_sender_reads_default_account(tmp_path):
    cfg = tmp_path / "config.toml"
    _write_himalaya_config(cfg, {
        "other": {"email": "other@example.com"},
        "main": {"email": "me@example.com", "display-name": "Me", "default": True},
    })
    assert resolve_sender(cfg) == "Me <me@example.com>"


def test_resolve_sender_falls_back_to_first_account(tmp_path):
    cfg = tmp_path / "config.toml"
    _write_himalaya_config(cfg, {
        "only": {"email": "solo@example.com", "display-name": "Solo"},
    })
    assert resolve_sender(cfg) == "Solo <solo@example.com>"


def test_resolve_sender_without_display_name(tmp_path):
    cfg = tmp_path / "config.toml"
    _write_himalaya_config(cfg, {
        "acct": {"email": "plain@example.com"},
    })
    assert resolve_sender(cfg) == "plain@example.com"


def test_resolve_sender_raises_on_missing_config(tmp_path):
    with pytest.raises(EmailError, match="config not found"):
        resolve_sender(tmp_path / "nope.toml")


def test_resolve_sender_raises_on_missing_email(tmp_path):
    cfg = tmp_path / "config.toml"
    cfg.write_text('[accounts.x]\ndisplay-name = "No Email"\n')
    with pytest.raises(EmailError, match="no 'email' field"):
        resolve_sender(cfg)


def test_resolve_sender_raises_on_no_accounts(tmp_path):
    cfg = tmp_path / "config.toml"
    cfg.write_text('[other]\nkey = "val"\n')
    with pytest.raises(EmailError, match="No accounts"):
        resolve_sender(cfg)
