"""Email sending via himalaya (CLI IMAP/SMTP client).

Used by the ``--email TO`` CLI flag: after the transcript file is generated,
it is attached to an email (with video metadata as body) and sent via the
user's pre-configured himalaya account.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from email.message import EmailMessage
from pathlib import Path

from .log import debug, info
from .util import TranscriptError, format_duration


HIMALAYA_BIN = "himalaya"
HIMALAYA_URL = "https://lib.rs/crates/himalaya"

# Reasonable RFC 5322-ish recipient check (single address, no display name).
_EMAIL_RE = re.compile(r"^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$")


class EmailError(TranscriptError):
    """Raised when email sending fails (missing himalaya, bad address, etc.)."""


def validate_email(address: str) -> None:
    """Raise EmailError if `address` does not look like a valid single recipient."""
    if not address or not _EMAIL_RE.match(address.strip()):
        raise EmailError(
            f"Invalid email address: {address!r}. "
            "Expected a single recipient like 'user@example.com'."
        )


def format_body(video_info: dict) -> str:
    """Build a plain-text email body from video metadata."""
    title = video_info.get("title") or "(unknown title)"
    channel = video_info.get("channel") or "(unknown channel)"
    url = video_info.get("url") or ""
    language = video_info.get("language") or "(auto)"
    duration_raw = video_info.get("duration") or 0
    duration = format_duration(duration_raw) if duration_raw else "unknown"
    upload_date = video_info.get("upload_date") or ""
    if upload_date:
        # YYYYMMDD -> YYYY-MM-DD (yt-dlp's upload_date format)
        upload_date = f"{upload_date[:4]}-{upload_date[4:6]}-{upload_date[6:8]}"

    lines = [
        "Transcript generated by yttranscript.",
        "",
        f"Title:    {title}",
        f"Channel:  {channel}",
    ]
    if url:
        lines.append(f"URL:      {url}")
    lines.append(f"Language: {language}")
    lines.append(f"Duration: {duration}")
    if upload_date:
        lines.append(f"Uploaded: {upload_date}")
    lines.append("")
    return "\n".join(lines)


def _build_mime(
    to: str,
    subject: str,
    body: str,
    attachment: Path,
) -> bytes:
    """Construct a MIME message with `body` as text + `attachment` as file."""
    msg = EmailMessage()
    msg["To"] = to
    msg["Subject"] = subject
    # From: leave unset; himalaya fills it from the configured account.
    msg.set_content(body)

    ctype = _guess_content_type(attachment)
    maintype, _, subtype = ctype.partition("/")
    data = attachment.read_bytes()
    filename = attachment.name
    msg.add_attachment(
        data,
        maintype=maintype or "application",
        subtype=subtype or "octet-stream",
        filename=filename,
    )
    return bytes(msg)


def _guess_content_type(path: Path) -> str:
    """Map common transcript extensions to MIME types (avoids sniffing)."""
    ext = path.suffix.lower()
    return {
        ".txt": "text/plain",
        ".json": "application/json",
        ".vtt": "text/vtt",
        ".srt": "application/x-subrip",
        ".pdf": "application/pdf",
        ".epub": "application/epub+zip",
        ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    }.get(ext, "application/octet-stream")


def send_email(
    to: str,
    subject: str,
    body: str,
    attachment: Path,
    himalaya_bin: str = HIMALAYA_BIN,
    timeout: float = 60.0,
) -> None:
    """Send `attachment` to `to` via himalaya.

    Raises EmailError if himalaya is missing, the address is invalid, the
    attachment does not exist, or himalaya exits non-zero.
    """
    validate_email(to)

    if shutil.which(himalaya_bin) is None:
        raise EmailError(
            f"himalaya is required for --email but was not found in PATH.\n"
            f"Install: {HIMALAYA_URL}"
        )

    if not attachment.exists():
        raise EmailError(f"Attachment not found: {attachment}")

    mime_bytes = _build_mime(to, subject, body, attachment)

    # Write to a temp file so the user's CWD is not polluted. himalaya reads
    # the full RFC 5322 message via -- (stdin) or -f <path>; -f is cleaner.
    with tempfile.NamedTemporaryFile(
        prefix="yttranscript_mail_", suffix=".eml", delete=False
    ) as tmp:
        tmp.write(mime_bytes)
        tmp_path = Path(tmp.name)

    try:
        # himalaya v1.2 takes the raw message path as a positional argument
        # (`himalaya message send [OPTIONS] [MESSAGE]...`). Earlier versions
        # also accepted a positional path; the deprecated `-f` flag was removed.
        cmd = [himalaya_bin, "message", "send", str(tmp_path)]
        debug(f"$ {' '.join(cmd[:3])} <eml>")
        info(f"Sending email to {to} ({attachment.name}, "
             f"{attachment.stat().st_size // 1024} KB)...")
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=timeout, check=False
        )
        if result.returncode != 0:
            stderr = (result.stderr or "").strip()
            raise EmailError(
                f"himalaya failed (exit {result.returncode}): {stderr or 'no output'}"
            )
    except subprocess.TimeoutExpired as e:
        raise EmailError(f"himalaya timed out after {timeout}s") from e
    finally:
        tmp_path.unlink(missing_ok=True)
